repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^(data/|notebooks/|.*.csv)
      - id: mixed-line-ending
      - id: check-yaml
        exclude: ^(.*README.md|data/|notebooks/|.*.csv|deployment/)
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
#        additional_dependencies: [ 'click==8.1.3' ]
        exclude: ^(.*README.md|data/|notebooks/|sql/|.*.csv)

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
